pipeline {
    agent any
    stages {
        stage("init") {
            steps {
                echo "Initializing the build..."
            }
        }
        stage("build") {
            steps {
                echo "Building the application..."
            }
        }

        stage("test") {
            steps {
                echo "Testing the application..."
            }
        }

        stage("deploy") {
            steps {
                echo "Deploying the application..."
            }
        }
    }
}
